//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Textos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentacion.Kuup.Recursos.Textos", typeof(Textos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Account_Boton_IniciarSecion {
            get {
                return ResourceManager.GetString("Account_Boton_IniciarSecion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia sesión en kuup.
        /// </summary>
        public static string Account_IniciarSecion {
            get {
                return ResourceManager.GetString("Account_IniciarSecion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KUUP.
        /// </summary>
        public static string Account_Kuup {
            get {
                return ResourceManager.GetString("Account_Kuup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario.
        /// </summary>
        public static string Account_NombreDeUsuario {
            get {
                return ResourceManager.GetString("Account_NombreDeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Account_Titulo {
            get {
                return ResourceManager.GetString("Account_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El equipo {0} e IP {1} no se encuentran registrados para iniciar sesión en Kuup.
        /// </summary>
        public static string Account_ValidaEquipo {
            get {
                return ResourceManager.GetString("Account_ValidaEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no tiene ningún perfil asignado.
        /// </summary>
        public static string Account_ValidaPerfil {
            get {
                return ResourceManager.GetString("Account_ValidaPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario y contraseña son incorrectos, favor de verificar.
        /// </summary>
        public static string Account_ValidaUsuarioContraseña {
            get {
                return ResourceManager.GetString("Account_ValidaUsuarioContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excepción de tipo: {0} Mensaje: {1} Código de Error: {2}.
        /// </summary>
        public static string Bitacora_TextoDeError {
            get {
                return ResourceManager.GetString("Bitacora_TextoDeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error no identificado, consultar bitácora para más detalle.
        /// </summary>
        public static string Bitacora_TextoTryCatchGenerico {
            get {
                return ResourceManager.GetString("Bitacora_TextoTryCatchGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --SELECCIONE--.
        /// </summary>
        public static string General_SELECCIONE {
            get {
                return ResourceManager.GetString("General_SELECCIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2020 Sistema de Inventario y Ventas Kuup | Desarrollado por  &lt;a href=&quot;&quot;&gt;SIR&lt;/a&gt;.
        /// </summary>
        public static string Kuup_Aplicacion {
            get {
                return ResourceManager.GetString("Kuup_Aplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar a la página de inicio.
        /// </summary>
        public static string NotFound_Boton_RegresarInicio {
            get {
                return ResourceManager.GetString("NotFound_Boton_RegresarInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error 404.
        /// </summary>
        public static string NotFound_Error404 {
            get {
                return ResourceManager.GetString("NotFound_Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página no encontrada, la ruta a la que se hace referencia no existe dentro del directorio, consultar a tu proveedor, si el problema persiste..
        /// </summary>
        public static string NotFound_Mensaje {
            get {
                return ResourceManager.GetString("NotFound_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página no encontrada.
        /// </summary>
        public static string NotFound_PaginaNoEncontrada {
            get {
                return ResourceManager.GetString("NotFound_PaginaNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Da click en el botón siguiente para salir y regresar al inicio..
        /// </summary>
        public static string NotFound_RegresarInicio {
            get {
                return ResourceManager.GetString("NotFound_RegresarInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Cantidad de Producto.
        /// </summary>
        public static string Producto_CantidadDeProductoNueva {
            get {
                return ResourceManager.GetString("Producto_CantidadDeProductoNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de Producto Total.
        /// </summary>
        public static string Producto_CantidadDeProductoTotal {
            get {
                return ResourceManager.GetString("Producto_CantidadDeProductoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultima Cantidad de Producto.
        /// </summary>
        public static string Producto_CantidadDeProductoUltima {
            get {
                return ResourceManager.GetString("Producto_CantidadDeProductoUltima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad minima a notificar.
        /// </summary>
        public static string Producto_CantidadMinima {
            get {
                return ResourceManager.GetString("Producto_CantidadMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad minima para aplicar mayoreo.
        /// </summary>
        public static string Producto_CantidadMinimaMayoreo {
            get {
                return ResourceManager.GetString("Producto_CantidadMinimaMayoreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo de Barras.
        /// </summary>
        public static string Producto_CodigoDeBarras {
            get {
                return ResourceManager.GetString("Producto_CodigoDeBarras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplica Mayoreo.
        /// </summary>
        public static string Producto_CveAplicaMayoreo {
            get {
                return ResourceManager.GetString("Producto_CveAplicaMayoreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso de Surtido.
        /// </summary>
        public static string Producto_CveAviso {
            get {
                return ResourceManager.GetString("Producto_CveAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificar Surtido por Correo.
        /// </summary>
        public static string Producto_CveCorreoSurtido {
            get {
                return ResourceManager.GetString("Producto_CveCorreoSurtido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        public static string Producto_CveEstatus {
            get {
                return ResourceManager.GetString("Producto_CveEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Producto_Descripcion {
            get {
                return ResourceManager.GetString("Producto_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Registro.
        /// </summary>
        public static string Producto_FechaDeRegistro {
            get {
                return ResourceManager.GetString("Producto_FechaDeRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Producto.
        /// </summary>
        public static string Producto_NombreDeProducto {
            get {
                return ResourceManager.GetString("Producto_NombreDeProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string Producto_NombreDeProveedor {
            get {
                return ResourceManager.GetString("Producto_NombreDeProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Producto.
        /// </summary>
        public static string Producto_NumeroDeProducto {
            get {
                return ResourceManager.GetString("Producto_NumeroDeProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string Producto_NumeroDeProveedor {
            get {
                return ResourceManager.GetString("Producto_NumeroDeProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio al mayoreo.
        /// </summary>
        public static string Producto_PrecioMayoreo {
            get {
                return ResourceManager.GetString("Producto_PrecioMayoreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio unitario.
        /// </summary>
        public static string Producto_PrecioUnitario {
            get {
                return ResourceManager.GetString("Producto_PrecioUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplica Mayoreo.
        /// </summary>
        public static string Producto_TextoAplicaMayoreo {
            get {
                return ResourceManager.GetString("Producto_TextoAplicaMayoreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso de Surtido.
        /// </summary>
        public static string Producto_TextoAviso {
            get {
                return ResourceManager.GetString("Producto_TextoAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificar Surtido por Correo.
        /// </summary>
        public static string Producto_TextoCorreoSurtido {
            get {
                return ResourceManager.GetString("Producto_TextoCorreoSurtido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        public static string Producto_TextoEstatus {
            get {
                return ResourceManager.GetString("Producto_TextoEstatus", resourceCulture);
            }
        }
    }
}
