//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Textos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentacion.Kuup.Recursos.Textos", typeof(Textos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string Account_Boton_IniciarSecion {
            get {
                return ResourceManager.GetString("Account_Boton_IniciarSecion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia sesión en kuup.
        /// </summary>
        public static string Account_IniciarSecion {
            get {
                return ResourceManager.GetString("Account_IniciarSecion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KUUP.
        /// </summary>
        public static string Account_Kuup {
            get {
                return ResourceManager.GetString("Account_Kuup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario.
        /// </summary>
        public static string Account_NombreDeUsuario {
            get {
                return ResourceManager.GetString("Account_NombreDeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Account_Titulo {
            get {
                return ResourceManager.GetString("Account_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo {0} e IP {1} no se encuentran registrados para iniciar sesión en Kuup.
        /// </summary>
        public static string Account_ValidaEquipo {
            get {
                return ResourceManager.GetString("Account_ValidaEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no tiene ningún perfil asignado.
        /// </summary>
        public static string Account_ValidaPerfil {
            get {
                return ResourceManager.GetString("Account_ValidaPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario y contraseña son incorrectos, favor de verificar.
        /// </summary>
        public static string Account_ValidaUsuarioContraseña {
            get {
                return ResourceManager.GetString("Account_ValidaUsuarioContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción de tipo: {0} Mensaje: {1} Código de Error: {2}.
        /// </summary>
        public static string Bitacora_TextoDeError {
            get {
                return ResourceManager.GetString("Bitacora_TextoDeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error no identificado, consultar bitácora para más detalle.
        /// </summary>
        public static string Bitacora_TextoTryCatchGenerico {
            get {
                return ResourceManager.GetString("Bitacora_TextoTryCatchGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --SELECCIONE--.
        /// </summary>
        public static string General_SELECCIONE {
            get {
                return ResourceManager.GetString("General_SELECCIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020 Sistema de Inventario y Ventas Kuup | Desarrollado por  &lt;a href=&quot;http://sir.sistemaseinnovacionsir.com/&quot;&gt;SIR&lt;/a&gt;.
        /// </summary>
        public static string Kuup_Aplicacion {
            get {
                return ResourceManager.GetString("Kuup_Aplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar a la página de inicio.
        /// </summary>
        public static string NotFound_Boton_RegresarInicio {
            get {
                return ResourceManager.GetString("NotFound_Boton_RegresarInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 404.
        /// </summary>
        public static string NotFound_Error404 {
            get {
                return ResourceManager.GetString("NotFound_Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página no encontrada, la ruta a la que se hace referencia no existe dentro del directorio, consultar a tu proveedor, si el problema persiste..
        /// </summary>
        public static string NotFound_Mensaje {
            get {
                return ResourceManager.GetString("NotFound_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página no encontrada.
        /// </summary>
        public static string NotFound_PaginaNoEncontrada {
            get {
                return ResourceManager.GetString("NotFound_PaginaNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da click en el botón siguiente para salir y regresar al inicio..
        /// </summary>
        public static string NotFound_RegresarInicio {
            get {
                return ResourceManager.GetString("NotFound_RegresarInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Cantidad de Producto.
        /// </summary>
        public static string Producto_CantidadDeProductoNueva {
            get {
                return ResourceManager.GetString("Producto_CantidadDeProductoNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de Producto Total.
        /// </summary>
        public static string Producto_CantidadDeProductoTotal {
            get {
                return ResourceManager.GetString("Producto_CantidadDeProductoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultima Cantidad de Producto.
        /// </summary>
        public static string Producto_CantidadDeProductoUltima {
            get {
                return ResourceManager.GetString("Producto_CantidadDeProductoUltima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad minima a notificar.
        /// </summary>
        public static string Producto_CantidadMinima {
            get {
                return ResourceManager.GetString("Producto_CantidadMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad minima para aplicar mayoreo.
        /// </summary>
        public static string Producto_CantidadMinimaMayoreo {
            get {
                return ResourceManager.GetString("Producto_CantidadMinimaMayoreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo de Barras.
        /// </summary>
        public static string Producto_CodigoDeBarras {
            get {
                return ResourceManager.GetString("Producto_CodigoDeBarras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplica Mayoreo.
        /// </summary>
        public static string Producto_CveAplicaMayoreo {
            get {
                return ResourceManager.GetString("Producto_CveAplicaMayoreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso de Surtido.
        /// </summary>
        public static string Producto_CveAviso {
            get {
                return ResourceManager.GetString("Producto_CveAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificar Surtido por Correo.
        /// </summary>
        public static string Producto_CveCorreoSurtido {
            get {
                return ResourceManager.GetString("Producto_CveCorreoSurtido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        public static string Producto_CveDeEstatus {
            get {
                return ResourceManager.GetString("Producto_CveDeEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Producto_Descripcion {
            get {
                return ResourceManager.GetString("Producto_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Registro.
        /// </summary>
        public static string Producto_FechaDeRegistro {
            get {
                return ResourceManager.GetString("Producto_FechaDeRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Producto.
        /// </summary>
        public static string Producto_NombreDeProducto {
            get {
                return ResourceManager.GetString("Producto_NombreDeProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        public static string Producto_NombreDeProveedor {
            get {
                return ResourceManager.GetString("Producto_NombreDeProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Producto.
        /// </summary>
        public static string Producto_NumeroDeProducto {
            get {
                return ResourceManager.GetString("Producto_NumeroDeProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        public static string Producto_NumeroDeProveedor {
            get {
                return ResourceManager.GetString("Producto_NumeroDeProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio al mayoreo.
        /// </summary>
        public static string Producto_PrecioMayoreo {
            get {
                return ResourceManager.GetString("Producto_PrecioMayoreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio unitario.
        /// </summary>
        public static string Producto_PrecioUnitario {
            get {
                return ResourceManager.GetString("Producto_PrecioUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplica Mayoreo.
        /// </summary>
        public static string Producto_TextoAplicaMayoreo {
            get {
                return ResourceManager.GetString("Producto_TextoAplicaMayoreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso de Surtido.
        /// </summary>
        public static string Producto_TextoAviso {
            get {
                return ResourceManager.GetString("Producto_TextoAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificar Surtido por Correo.
        /// </summary>
        public static string Producto_TextoCorreoSurtido {
            get {
                return ResourceManager.GetString("Producto_TextoCorreoSurtido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        public static string Producto_TextoDeEstatus {
            get {
                return ResourceManager.GetString("Producto_TextoDeEstatus", resourceCulture);
            }
        }
    }
}
