//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public short BIT_NUM_BITACORA { get; set; }
        public short BIT_NUM_PANTALLA { get; set; }
        public byte BIT_NUM_FUNCIONALIDAD { get; set; }
        public String BIT_NOM_FUNCION_COD { get; set; }
        public String BIT_DETALLE { get; set; }
        public System.DateTime BIM_FECHA_BITACORA { get; set; }
    
        public virtual Pantalla Pantalla { get; set; }
    }
}
