//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraCorreo
    {
        public short BIM_NUM_PANTALLA { get; set; }
        public string BIM_CORREO { get; set; }
        public string BIM_ASUNTO { get; set; }
        public string BIM_MENSAJE { get; set; }
        public System.DateTime BIM_FECHA_ENVIO { get; set; }
        public System.DateTime BIM_FECHA_REENVIO { get; set; }
        public string BIM_MESAJE_ERROR { get; set; }
        public byte BIM_CVE_ESTATUS { get; set; }
    
        public virtual Pantalla Pantalla { get; set; }
    }
}
