//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claves
    {
        public byte CVE_NUM_CLAVE { get; set; }
        public byte CVE_NUM_SEC_CLAVE { get; set; }
        public string CVE_NOM_CLAVE { get; set; }
        public string CVE_DESCRIPCION { get; set; }
        public string CVE_DATO_ADICIONAL_I { get; set; }
        public string CVE_DATO_ADICIONAL_II { get; set; }
        public byte CVE_CVE_ESTATUS { get; set; }
    }
}
