//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguraPaquete
    {
        public short CNP_NUM_PRODUCTO_PADRE { get; set; }
        public short CNP_NUM_PRODUCTO_HIJO { get; set; }
        public decimal CNP_PRECIO_PRODUCTO_PADRE { get; set; }
        public Nullable<decimal> CNP_PRECIO_PRODUCTO_HIJO { get; set; }
        public decimal CNP_IMPORTE_TOTAL { get; set; }
    }
}
