//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionalidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionalidad()
        {
            this.FuncionPerfil = new HashSet<FuncionPerfil>();
        }
    
        public short FUN_NUM_PANTALLA { get; set; }
        public byte FUN_NUM_FUNCIONALIDAD { get; set; }
        public String FUN_NOM_FUNCIONALIDAD { get; set; }
        public byte FUN_CVE_ESTATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncionPerfil> FuncionPerfil { get; set; }
        public virtual Pantalla Pantalla { get; set; }
    }
}
