//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionPerfil
    {
        public short FUP_NUM_PANTALLA { get; set; }
        public byte FUP_NUM_FUNCIONALIDAD { get; set; }
        public byte FUP_NUM_PERFIL { get; set; }
        public byte FUP_CVE_ESTATUS { get; set; }
    
        public virtual Funcionalidad Funcionalidad { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
