//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPRegistradas
    {
        public short IPR_NUM_USUARIO { get; set; }
        public string IPR_TERMINAL { get; set; }
        public string IPR_IP { get; set; }
        public byte IPR_CVE_TIPOACCESO { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
