//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcaAudit
    {
        public short MRA_ID_AUDIT { get; set; }
        public string MRA_TERMINAL { get; set; }
        public string MRA_IP { get; set; }
        public string MRA_VERSION { get; set; }
        public string MRA_NOM_USUARIO { get; set; }
        public System.DateTime MRA_FECHA_BASE { get; set; }
        public string MRA_NOM_FUNCIONALIDAD { get; set; }
        public short MRA_NUM_MARCA { get; set; }
        public string MRA_NOM_MARCA { get; set; }
        public byte MRA_CVE_ESTATUS { get; set; }
        public string MRA_TXT_ESTATUS { get; set; }
    }
}
