//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public short MEN_NUM_MENU { get; set; }
        public short MEN_NUM_PADRE { get; set; }
        public byte MEN_NUM_ORDEN { get; set; }
        public string MEN_NOM_MENU { get; set; }
        public short MEN_NUM_PANTALLA { get; set; }
        public byte MEN_CVE_ESTATUS { get; set; }
    }
}
