//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public byte PAR_CVE_TIPO { get; set; }
        public String PAR_NOM_PARAMETRO { get; set; }
        public String PAR_VALOR_PARAMETRO { get; set; }
        public String PAR_DESCRIPCION { get; set; }
    }
}
