//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoAudit
    {
        public short PRO_ID_AUDIT { get; set; }
        public string PRO_TERMINAL { get; set; }
        public string PRO_IP { get; set; }
        public string PRO_VERSION { get; set; }
        public string PRO_NOM_USUARIO { get; set; }
        public System.DateTime PRO_FECHA_BASE { get; set; }
        public string PRO_NOM_FUNCIONALIDAD { get; set; }
        public short PRO_NUM_PRODUCTO { get; set; }
        public string PRO_CODIGO_BARRAS { get; set; }
        public System.DateTime PRO_FECHA_REGISTRO { get; set; }
        public short PRO_CANT_PRODUCTO_ULTIMA { get; set; }
        public short PRO_CANT_PRODUCTO_NUEVA { get; set; }
        public short PRO_CANT_PRODUCTO_TOTAL { get; set; }
        public string PRO_NOM_PRODUCTO { get; set; }
        public string PRO_DESCRIPCION { get; set; }
        public byte PRO_CVE_TIPO_PRODUCTO { get; set; }
        public byte PRO_CVE_MARCA { get; set; }
        public byte PRO_CVE_AVISO { get; set; }
        public byte PRO_CVE_CORREO_SURTIDO { get; set; }
        public short PRO_CAT_MINIMA { get; set; }
        public Nullable<byte> PRO_NUM_PROVEEDOR { get; set; }
        public decimal PRO_PRECIO_UNITARIO { get; set; }
        public byte PRO_CVE_ESTATUS { get; set; }
        public string PRO_TXT_TIPO_PRODUCTO { get; set; }
        public string PRO_TXT_MARCA { get; set; }
        public string PRO_TXT_AVISO { get; set; }
        public string PRO_TXT_CORREO_SURTIDO { get; set; }
        public string PRO_NOM_PROVEEDOR { get; set; }
        public string PRO_TXT_ESTATUS { get; set; }
    }
}
