//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public byte PRV_NUM_PROVEEDOR { get; set; }
        public string PRV_NOM_PROVEEDOR { get; set; }
        public System.DateTime PRV_FECHA_REGISTRO { get; set; }
        public byte PRV_CVE_SURTIDO_POR_CORREO { get; set; }
        public string PRV_CORREO { get; set; }
        public string PRV_ASUNTO { get; set; }
        public string PRV_MENSAJE { get; set; }
        public byte PRV_CVE_ESTATUS { get; set; }
    }
}
