//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Surtido = new HashSet<Surtido>();
        }
    
        public byte PRV_NUM_PROVEEDOR { get; set; }
        public string PRV_NOM_PROVEEDOR { get; set; }
        public System.DateTime PRV_FECHA_REGISTRO { get; set; }
        public byte PRV_CVE_SURTIDO_POR_CORREO { get; set; }
        public string PRV_CORREO { get; set; }
        public string PRV_ASUNTO { get; set; }
        public string PRV_MENSAJE { get; set; }
        public byte PRV_CVE_ESTATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Surtido> Surtido { get; set; }
    }
}
