//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoProducto
    {
        public short TPO_NUM_TIPO_PRODUCTO { get; set; }
        public string TPO_NOM_TIPO_PRODUCTO { get; set; }
        public byte TPO_CVE_ESTATUS { get; set; }
    }
}
