//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoProductoAudit
    {
        public short TPO_ID_AUDIT { get; set; }
        public string TPO_TERMINAL { get; set; }
        public string TPO_IP { get; set; }
        public string TPO_VERSION { get; set; }
        public string TPO_NOM_USUARIO { get; set; }
        public System.DateTime TPO_FECHA_BASE { get; set; }
        public string TPO_NOM_FUNCIONALIDAD { get; set; }
        public short TPO_NUM_TIPO_PRODUCTO { get; set; }
        public string TPO_NOM_TIPO_PRODUCTO { get; set; }
        public byte TPO_CVE_ESTATUS { get; set; }
        public string TPO_TXT_ESTATUS { get; set; }
    }
}
