//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public short VEN_FOLIO_OPERACION { get; set; }
        public short VEN_NUM_PRODUCTO { get; set; }
        public string VEN_CODIGO_BARRAS { get; set; }
        public short VEN_CANT_PRODUCTO { get; set; }
        public decimal VEN_PRECIO_UNITARIO { get; set; }
        public decimal VEN_IMPORTE_PRODUCTO { get; set; }
    
        public virtual VentaTotal VentaTotal { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
