//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public short VEN_FOLIO_OPERACION { get; set; }
        public short VEN_NUM_PRODUCTO { get; set; }
        public string VEN_CODIGO_BARRAS { get; set; }
        public short VEN_NUM_TIPO_PRODUCTO { get; set; }
        public Nullable<short> VEN_NUM_MARCA { get; set; }
        public short VEN_CANT_PRODUCTO { get; set; }
        public decimal VEN_PRECIO_UNITARIO { get; set; }
        public decimal VEN_IMPORTE_PRODUCTO { get; set; }
        public byte VEN_CVE_ESTATUS { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual VentaTotal VentaTotal { get; set; }
    }
}
