//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaTotal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VentaTotal()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public short VET_FOLIO_OPERACION { get; set; }
        public System.DateTime VET_FECHA_OPERACION { get; set; }
        public short VET_NUM_USUARIO { get; set; }
        public string VET_NOM_CLIENTE { get; set; }
        public decimal VET_IMPORTE_BRUTO { get; set; }
        public Nullable<decimal> VET_IVA { get; set; }
        public byte VET_CVE_APLICADESCUENTO { get; set; }
        public string VET_PORCENTAJE { get; set; }
        public decimal VET_IMPORTE_NETO { get; set; }
        public decimal VET_IMPORTE_ENTREGADO { get; set; }
        public decimal VET_IMPORTE_CAMBIO { get; set; }
        public byte VET_CVE_ESTATUS { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
