//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViAgenda
    {
        public short AGN_NUM_AGENDA { get; set; }
        public System.DateTime AGN_FECHA_ALTA { get; set; }
        public System.DateTime AGN_FECHA_INI_EVENTO { get; set; }
        public System.DateTime AGN_FECHA_FIN_EVENTO { get; set; }
        public short AGN_NUM_USUARIO { get; set; }
        public byte AGN_CVE_NOTIFICA { get; set; }
        public string AGN_DESCRIPCION { get; set; }
        public byte AGN_CVE_ESTATUS { get; set; }
        public string AGN_NOM_USUARIO { get; set; }
        public string AGN_TXT_NOTIFICA { get; set; }
        public string AGN_TXT_ESTATUS { get; set; }
    }
}
