//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViAsignaMarca
    {
        public byte AMA_NUM_MARCA { get; set; }
        public byte AMA_CVE_TIPO_PRODUCTO { get; set; }
        public string AMA_NOM_MARCA { get; set; }
        public string AMA_TXT_TIPO_PRODUCTO { get; set; }
    }
}
