//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViBitacoraCorreo
    {
        public short BIM_NUM_PANTALLA { get; set; }
        public string BIM_CORREO { get; set; }
        public string BIM_ASUNTO { get; set; }
        public string BIM_MENSAJE { get; set; }
        public System.DateTime BIM_FECHA_ENVIO { get; set; }
        public System.DateTime BIM_FECHA_REENVIO { get; set; }
        public string BIM_MESAJE_ERROR { get; set; }
        public byte BIM_CVE_ESTATUS { get; set; }
        public string BIM_NOM_PANTALLA { get; set; }
        public string BIM_TXT_ESTATUS { get; set; }
    }
}
