//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViBitacora
    {
        public short BIT_NUM_BITACORA { get; set; }
        public short BIT_NUM_PANTALLA { get; set; }
        public byte BIT_NUM_FUNCIONALIDAD { get; set; }
        public string BIT_NOM_FUNCION_COD { get; set; }
        public string BIT_DETALLE { get; set; }
        public System.DateTime BIM_FECHA_BITACORA { get; set; }
        public string BIT_NOM_PANTALLA { get; set; }
        public string BIT_NOM_FUNCIONALIDAD { get; set; }
    }
}
