//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViClaves
    {
        public byte CVE_NUM_CLAVE { get; set; }
        public byte CVE_NUM_SEC_CLAVE { get; set; }
        public string CVE_NOM_CLAVE { get; set; }
        public string CVE_DESCRIPCION { get; set; }
        public string CVE_DATO_ADICIONAL_I { get; set; }
        public string CVE_DATO_ADICIONAL_II { get; set; }
        public byte CVE_CVE_ESTATUS { get; set; }
        public string CVE_TXT_ESTATUS { get; set; }
    }
}
