//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViConfiguraMayoreo
    {
        public short COM_NUM_MAYOREO { get; set; }
        public short COM_NUM_PRODUCTO { get; set; }
        public string COM_CODIGO_BARRAS { get; set; }
        public byte COM_CVE_APLICA_PAQUETES { get; set; }
        public byte COM_CANTIDAD_MINIMA { get; set; }
        public Nullable<byte> COM_CANTIDAD_MAXIMA { get; set; }
        public decimal COM_PRECIO_MAYOREO { get; set; }
        public string COM_NOM_PRODUCTO { get; set; }
    }
}
