//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViFuncionPerfil
    {
        public short FUP_NUM_PANTALLA { get; set; }
        public byte FUP_NUM_FUNCIONALIDAD { get; set; }
        public byte FUP_NUM_PERFIL { get; set; }
        public byte FUP_CVE_ESTATUS { get; set; }
        public string FUP_NOM_PANTALLA { get; set; }
        public string FUP_NOM_FUNCIONALIDAD { get; set; }
        public string FUP_NOM_PERFIL { get; set; }
        public string FUP_TXT_ESTATUS { get; set; }
    }
}
