//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViFuncionalidad
    {
        public short FUN_NUM_PANTALLA { get; set; }
        public byte FUN_NUM_FUNCIONALIDAD { get; set; }
        public string FUN_NOM_FUNCIONALIDAD { get; set; }
        public byte FUN_CVE_ESTATUS { get; set; }
        public string FUN_TXT_ESTATIS { get; set; }
    }
}
