//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViFuncionalidad
    {
        public short FUN_NUM_PANTALLA { get; set; }
        public byte FUN_NUM_FUNCIONALIDAD { get; set; }
        public string FUN_NOM_FUNCIONALIDAD { get; set; }
        public byte FUN_CVE_ESTATUS { get; set; }
        public string FUN_NOM_PANTALLA { get; set; }
        public string FUN_TXT_ESTATUS { get; set; }
    }
}
