//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViIPRegistradas
    {
        public short IPR_NUM_USUARIO { get; set; }
        public String IPR_TERMINAL { get; set; }
        public String IPR_IP { get; set; }
        public byte IPR_CVE_TIPOACCESO { get; set; }
        public String IPR_NOM_USUARIO { get; set; }
        public String IPR_TXT_TIPOACCESO { get; set; }
    }
}
