//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViMenu
    {
        public short MEN_NUM_MENU { get; set; }
        public short MEN_NUM_PADRE { get; set; }
        public byte MEN_NUM_ORDEN { get; set; }
        public string MEN_NOM_MENU { get; set; }
        public short MEN_NUM_PANTALLA { get; set; }
        public string MEN_URL_INT { get; set; }
        public byte MEN_CVE_ESTATUS { get; set; }
        public string MEN_NOM_PANTALLA { get; set; }
        public string MEN_NOM_PANTALLA_INT { get; set; }
        public string MEN_TXT_ESTATUS { get; set; }
    }
}
