//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViPantalla
    {
        public short PAN_NUM_PANTALLA { get; set; }
        public String PAN_NOM_PANTALLA { get; set; }
        public String PAN_NOM_PANTALLA_INT { get; set; }
        public String PAN_DESCRIPCION { get; set; }
        public byte PAN_CVE_MANEJO_INTERNO { get; set; }
        public String PAN_LLAVE { get; set; }
        public byte PAN_CVE_ESTATUS { get; set; }
        public String PAN_TXT_MANEJO_INTERNO { get; set; }
        public String PAN_TXT_ESTATUS { get; set; }
    }
}
