//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViPantallaPerfil
    {
        public short PAP_NUM_PANTALLA { get; set; }
        public byte PAP_NUM_PERFIL { get; set; }
        public byte PAP_CVE_ESTATUS { get; set; }
        public String PAP_NOM_PANTALLA { get; set; }
        public String PAP_NOM_PANTALLA_INT { get; set; }
        public String PAP_NOM_PERFIL { get; set; }
        public String PAP_TXT_ESTATUS { get; set; }
    }
}
