//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViParametro
    {
        public byte PAR_CVE_TIPO { get; set; }
        public string PAR_NOM_PARAMETRO { get; set; }
        public string PAR_VALOR_PARAMETRO { get; set; }
        public string PAR_DESCRIPCION { get; set; }
        public string PAR_TXT_TIPO { get; set; }
    }
}
