//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViPerfil
    {
        public byte PER_NUM_PERFIL { get; set; }
        public string PER_NOM_PERFIL { get; set; }
        public byte PER_CVE_TIPO_PERFIL { get; set; }
        public byte PER_CVE_ESTATUS { get; set; }
        public string PER_TXT_TIPO_PERFIL { get; set; }
        public string PER_TXT_ESTATUS { get; set; }
    }
}
