//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViPerfil
    {
        public byte PER_NUM_PERFIL { get; set; }
        public string PER_NOM_PERFIL { get; set; }
        public byte PER_CVE_TIPO_PERFIL { get; set; }
        public byte PER_CVE_ESTATUS { get; set; }
        public string PER_TXT_TIPO_PERFIL { get; set; }
        public string PER_TXT_ESTATUS { get; set; }
    }
}
