//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViSurtido
    {
        public short SUR_FOLIO_SURTIDO { get; set; }
        public byte SUR_CVE_APLICA_PROVEEDOR { get; set; }
        public Nullable<byte> SUR_NUM_PROVEEDOR { get; set; }
        public Nullable<short> SUR_NUM_USUARIO { get; set; }
        public short SUR_NUM_PRODUCTO { get; set; }
        public string SUR_CODIGO_BARRAS { get; set; }
        public short SUR_CANT_PREVIA { get; set; }
        public short SUR_CANT_NUEVA { get; set; }
        public Nullable<decimal> SUR_PRECIO_UNITARIO { get; set; }
        public Nullable<decimal> SUR_COSTO_TOTAL { get; set; }
        public System.DateTime SUR_FECHA_SURTIDO { get; set; }
        public byte SUR_CVE_ESTATUS { get; set; }
        public string SUR_TXT_APLICA_MAYOREO { get; set; }
        public string SUR_NOM_PROVEEDOR { get; set; }
        public string SUR_NOM_USUARIO { get; set; }
        public string SUR_NOM_PRODUCTO { get; set; }
        public string SUR_TXT_ESTATUS { get; set; }
    }
}
