//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViUsuario
    {
        public short USU_NUM_USUARIO { get; set; }
        public String USU_NOM_USUARIO { get; set; }
        public String USU_NOM_PERS { get; set; }
        public String USU_APP_PERS { get; set; }
        public String USU_APM_PERS { get; set; }
        public String USU_CORREO { get; set; }
        public String USU_PASSWORD { get; set; }
        public System.DateTime USU_FECHA_REGISTRO { get; set; }
        public Nullable<System.DateTime> USU_FECHA_CANCELACION { get; set; }
        public byte USU_CVE_ESTATUS { get; set; }
        public String USU_TXT_ESTATUS { get; set; }
    }
}
