//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViUsuarioPerfil
    {
        public byte USP_NUM_PERFIL { get; set; }
        public short USP_NUM_USUARIO { get; set; }
        public byte USP_CVE_ESTATUS { get; set; }
        public string USP_NOM_PERFIL { get; set; }
        public string USP_NOM_USUARIO { get; set; }
        public string USP_CORREO { get; set; }
        public string USP_TXT_ESTATUS { get; set; }
    }
}
