name: Nombre de Usuario
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Usuario
        run: |
          echo $USER_NAME
        env: 
          USER_NAME: ${{ secrets.USER_NAME }}
